apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: fmu-to-resqml
spec:
  environments:
    - name: prod
      build:
        from: main
    - name: dev
      build:
        from: main
      enabled: false
    - name: test
      build:
        from: main
      enabled: false
    - name: preview
      build:
        from: main
      enabled: false
  components:
    - name: api
      identity:
        azure:
          clientId: 8c303b49-e196-41dc-9300-d9e3fb6d04bf
      resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 1000m
      src: "."
      publicPort: http
      ports:
        - name: http
          port: 5000
